supu=input('Anna sukupuolesi:')
arvo=float(input('Anna hemoglobiiniarvosi:'))
if supu=='Mies' and arvo<=134:print('Hemoglobiiniarvosi on alhainen.')
elif supu=='Mies' and arvo>=134 and arvo<195:print('Hemoglobiiniarvosi on normaali.')
elif supu=='Mies' and arvo>=195:print('Hemoglobiiniarvosi on korkea.')
elif supu=='mies' and arvo<=134:print('Hemoglobiiniarvosi on alhainen.')
elif supu=='mies' and arvo>=134 and arvo<195:print('Hemoglobiiniarvosi on normaali.')
elif supu=='mies' and arvo>=195:print('Hemoglobiiniarvosi on korkea.')
else:
    if supu=='Nainen' and arvo<=117:print('Hemoglobiiniarvosi on alhainen.')
    elif supu=='Nainen' and arvo>=117 and arvo<175:print('Hemoglobiiniarvosi on normaali.')
    elif supu=='Nainen' and arvo>=175:print('Hemoglobiiniarvosi on korkea.')
    elif supu=='nainen' and arvo<=117:print('Hemoglobiiniarvosi on alhainen.')
    elif supu=='nainen' and arvo>=117 and arvo<175:print('Hemoglobiiniarvosi on normaali.')
    elif supu=='nainen' and arvo>=175:print('Hemoglobiiniarvosi on korkea.')