huone = input('Kerro hyttiluokka: ')
if huone=='LUX':print('LUX on parvekkeellinen hytti yläkannella.')
elif huone=='lux':print('LUX on parvekkeellinen hytti yläkannella.')
elif huone=='A':print('A on ikkunallinen hytti autokannen yläpuolella.')
elif huone=='a':print('A on ikkunallinen hytti autokannen yläpuolella.')
elif huone=='B':print('B on ikkunaton hytti autokannen yläpuolella.')
elif huone=='b':print('B on ikkunaton hytti autokannen yläpuolella.')
elif huone=='C':print('C on ikkunaton hytti autokannen alapuolella.')
elif huone=='c':print('C on ikkunaton hytti autokannen alapuolella.')
else: print('Virheellinen hyttiluokka.')